[app]
name = "WebApp"
version = "0.0.1"
port = 5050

[cache]
host = "localhost"
port = 6379
max_idle = 100
idle_timeout = 120
enabled = true

[database]
host = "localhost"
port = 26257
name = "api02"
sslmode = "disable"
username = "root"
password = ""
